// Code generated by generator. DO NOT EDIT.

package b

import "testing"

func nonTestHelper(b int) {}

func helperWithoutHelper(b *testing.B) {} // want "test helper function should start from b.Helper()"

func helperWithHelper(b *testing.B) {
	b.Helper()
}

func helperWithEmptyStringBeforeHelper(b *testing.B) {

	b.Helper()
}

func helperWithHelperAfterAssignment(b *testing.B) { // want "test helper function should start from b.Helper()"
	_ = 0
	b.Helper()
}

func helperWithHelperAfterOtherCall(b *testing.B) { // want "test helper function should start from b.Helper()"
	f()
	b.Helper()
}

func helperWithHelperAfterOtherSelectionCall(b *testing.B) { // want "test helper function should start from b.Helper()"
	b.Fail()
	b.Helper()
}

func helperWithNotFirst(s string, b *testing.B, i int) { // want "parameter \\*testing.B should be the first"
	b.Helper()
}

func helperWithIncorrectName(o *testing.B) { // want "parameter \\*testing.B should have name b"
	o.Helper()
}

func f() {}
