issues:
  exclude-dirs:
    - pkg/analyzer/testdata

linters:
  enable-all: true
  disable:
    - cyclop
    - depguard # Not looks useful for this project
    - dupl
    - exhaustruct # Make use of zero-values and partial initialization.
    - gocognit
    - err113
    - mnd
    - lll
    - nestif
    - nilnil
    - nlreturn
    - paralleltest
    - prealloc
    - varnamelen
    - wsl # Deprecated, replaced by wsl_v5
    - tenv # Deprecated, replaced by usetesting

linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  nolintlint:
    require-explanation: true
    require-specific: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/kulti/thelper)
