version: "2"

run:
  skip-dirs:
    - pkg/analyzer/testdata

linters:
  default: all
  disable:
    - cyclop
    - depguard # Not looks useful for this project
    - dupl
    - exhaustruct # Make use of zero-values and partial initialization.
    - gocognit
    - err113
    - mnd
    - lll
    - nestif
    - nilnil
    - nlreturn
    - paralleltest
    - prealloc
    - varnamelen
    - wsl_v5
  settings:
    goconst:
      min-len: 2
      min-occurrences: 3
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: true

formatters:
  enable:
    - gci
  settings:
    gci:
      local-prefixes: github.com/kulti/thelper
