// Code generated by generator. DO NOT EDIT.

package t

import "testing"

func nonTestHelper(t int) {}

func helperWithoutHelper(t *testing.T) {} // want "test helper function should start from t.Helper()"

func helperWithHelper(t *testing.T) {
	t.Helper()
}

func helperWithEmptyStringBeforeHelper(t *testing.T) {

	t.Helper()
}

func helperWithHelperAfterAssignment(t *testing.T) { // want "test helper function should start from t.Helper()"
	_ = 0
	t.Helper()
}

func helperWithHelperAfterOtherCall(t *testing.T) { // want "test helper function should start from t.Helper()"
	f()
	t.Helper()
}

func helperWithHelperAfterOtherSelectionCall(t *testing.T) { // want "test helper function should start from t.Helper()"
	t.Fail()
	t.Helper()
}

func helperWithNotFirst(s string, t *testing.T, i int) { // want "parameter \\*testing.T should be the first"
	t.Helper()
}

func helperWithIncorrectName(o *testing.T) { // want "parameter \\*testing.T should have name t"
	o.Helper()
}

func f() {}
